In [5]:

import math
import cv2
import numpy as np

img =np.zeros((800,800,3),np.uint8)
StartingPointX=int(input("enter the x value of starting point"))
StartingPointY=int(input("enter the y value of starting point"))
print(StartingPointX,StartingPointY)
angle=float(input("enter the direction"))
speed=float(input("enter the speed"))
time=int(input("enter the time"))
hypo=time*(speed/1000)*60*60
print(hypo)
print(math.sin(103*3.14/180))
endingY=math.sin(angle*3.14/180)*hypo+StartingPointY
endingX=math.cos(angle*3.14/180)*hypo+StartingPointX
print(endingX,endingY)
cv2.circle(img,(StartingPointX,StartingPointY),2,(255,255,0),5)
cv2.circle(img,(int(endingX),int(endingY)),2,(0,0,255),5)
cv2.line(img,(StartingPointX,StartingPointY),(int(endingX),int(endingY)),(255,255,0),1)
cv2.imshow("image",img)
cv2.waitKey(0)


25 25
74.13119999999998
0.9745746696624553
8.389943368906192 97.24638975168139
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [3]:

import cv2
import numpy as np
  



def draw_circle(event, x, y, flags, param):
    """Mouse callback function"""
    global circles
    if event == cv2.EVENT_LBUTTONDBLCLK:
        circles.append((x, y))
    if event == cv2.EVENT_RBUTTONDBLCLK:
        circles[:] = []
    elif event == cv2.EVENT_RBUTTONDOWN:
        try:
            circles.pop()
        except (IndexError):
            print("no circles to delete")
   



circles = []


image = np.zeros((300, 300, 3),np.uint8)

cv2.namedWindow('Image mouse')
cv2.setMouseCallback('Image mouse', draw_circle)

cv2.putText(image, 'Double left click: add a circle', (10,200), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255))
cv2.putText(image, 'Simple right click: delete last circle', (10,225), cv2.FONT_HERSHEY_SIMPLEX, 0.4,
                (255, 255, 255))
cv2.putText(image, 'Double right click: delete all circle', (10,250), cv2.FONT_HERSHEY_SIMPLEX, 0.4,
                (255, 255, 255))
cv2.putText(image, 'Press \'q\' to exit', (10,275), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255))

clone = image.copy()

while True:

    image = clone.copy()

    for pos in circles:
        cv2.circle(image, pos, 30, (0,0,255), -1)

   
    cv2.imshow('Image mouse', image)

    
    if cv2.waitKey(400) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

height = 50
width = 50
img1 = np.zeros((height,width,3), np.uint8)
img1[:,:] = (255,0,0)

img2 = np.zeros((height,width,3), np.uint8)
img2[:,:] = (0,255,0)

img3 = np.zeros((height,width,3), np.uint8)
img3[:,:] = (0,0,255)

img4 = np.zeros((height,width,3), np.uint8)
img4[:,:] = (255,255,255)

img5=np.hstack((img1,img2))
img6=np.hstack((img3,img4))
img7=np.vstack((img5,img6))

imgResized = cv2.resize(img7,(200,200))

cv2.imshow("Image",imgResized)
cv2.waitKey(0)


In [ ]:
import cv2
import numpy as np



cap = cv2.VideoCapture(0)
cap.set(3, 1280)
cap.set(4, 720)
cap.set(10, 70)

frame_width = int(cap.get(3))
frame_height = int(cap.get(4))

size = (frame_width, frame_height)

result = cv2.VideoWriter('H:\Vortex/task1/testvideo.avi',
                         cv2.VideoWriter_fourcc(*'MJPG'),
                         10, size)


while True:
        success, img = cap.read()
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        imgR = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
        imgH = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        C = input()
        print(C)
        if(C=='Q'):
            exit()
        elif(C=='R'):
            cv2.imshow("Output8", imgR)
            cv2.waitKey(0)
        elif(C=='C'):
            cv2.imwrite("H:\Vortex/task1/test.png", img)
        elif(C=='S'):
            i = 0
            while i < 100:
                success, img = cap.read()
                result.write(img)
                i = i + 1
        elif(C=='G'):
            cv2.imshow("Output7", gray)
            cv2.waitKey(0)
        elif(C=='H'):
            cv2.imshow("Output6", imgH)
            cv2.waitKey(0)
        elif(C=='X'):
            cv2.imshow("Output1", imgH)
            cv2.imshow("Output2", gray)
            cv2.imshow("Output3", img)
            cv2.imshow("Output4", imgR)
            cv2.waitKey(0)
        elif(C=='Z'):
            cv2.imshow("Output5", img)
            cv2.waitKey(0)